export const ScreenName = {
  SIGN_UP: 'Signup',
  LOGIN: 'Login',
  VERIFICATION: 'Verification',
  FORGET_PASSWORD: 'ForgetPassword',
  VERIFICATION_SUCCESS: 'VerificationSuccess',
  ON_BOARDING: 'OnBoarding',
  MAIN: 'Main',
  CARD_INFO: 'CardInfo',
  CARD_SELECTION: 'CardSelection',
  HOME: 'Home',
  SEARCH: 'Search',
  TIME_SELECTION: 'TimeSelection',
  BOOK_TIME: 'BookTime',
  PENDING: 'Pending',
  ROLE_SELECT: 'RoleSelect',
  CREATE_PASSWORD: 'CreatePassword',
  GET_STARTED: 'GetStarted',
  LOCATION_AND_NOTIFICATION1: 'LocationAndNotification1',
  LOCATION_AND_NOTIFICATION2: 'LocationAndNotification2',
  ACTIVITY_LIST: 'ActivityList',
  TRIP_DETAILS: 'TripDetails',
  ACTIVITY: 'Activity',
  Profile: 'Profile',
  WHERE_TO: 'WhereTo',
};
